### ISSUE TITLE
CSS abbreviations with special syntax after colon don't get expanded properly

### ISSUE THREAD

**Issue by gushuro** [emmetio/expand-abbreviation#18]
When some CSS abbreviations include some abbreviation for the property value, they don't get expanded as shown in Emmet's cheat sheet.

Examples: `c:r` gets expanded to `color: r;` instead of `color:rgb(0, 0, 0);`.
Same happens to `c:ra` and for other property names abbreviations such as `bxsh`

Also, when expanding `trf:t3`, I get `transform: translate(x, y) 3px;` instead of `transform: translate3d(tx, ty, tz);`

**Comment by sergeche** [comment]
Emmet 2.0 introduces new snippets and expanding options. There’s no `c:r` abbreviation anymore: https://github.com/emmetio/snippets/blob/master/css.json The cheat sheet displays snippets for old Emmet, version 2.0 is not announced yet.

As for `trf:t3` — it’s a bit tricky, since character-to-number transition considered as new value, I’ll try to find solution for this problem. Right now, you can try `trf:td` instead
