### ISSUE TITLE
Shouldn't expand CSS when there is no possible output

### ISSUE THREAD

**Issue by tholman** [emmetio/expand-abbreviation#5]
Running expand on some css (with syntax set to css) like `.className` (where there are no possible expansions) will return `NaNClassName`, should it return either `.className` or `null`?

**Comment by sergeche** [comment]
Yes, it’s a but in current implementation. Emmet shouldn’t even allow such abbreviations to be exapanded

**Comment by tholman** [comment]
Ahh, so the ticket belongs in a different repository to this one?

**Comment by sergeche** [comment]
It’s OK to keep it here since :) I’ll get back to this issue a bit later

**Comment by ramya-rao-a** [comment]
@sergeche I fixed this issue in VS Code by adding a validation on the first letter of the css abbreviation.
If the first letter doesn't match the regex `/a-z,A-Z,!,@,#]/`, I avoid calling emmet.

Would you be open to a PR to add a similar check for the `expand-abbreviation` module?

**Comment by sergeche** [comment]
@ramya-rao-a not that simple. Abbreviation can start with `@` which is commonly used for at-rules, but can’t start with `!` or `#` as *property* abbreviation, only as *value*. In your example, `#my` would produce the same invalid result as `.class`. I think this check should be on editor part or at least as a separate module/helper, but not in actual `expand-abbreviation` module

**Comment by ramya-rao-a** [comment]
Got it.

Speaking of _value abbreviations_,  `!`  (for !important) and `#` (for colors) are the only default ones correct?

How can we define custom snippets for value abbreviations?
For example: defining a snippet like `"hello": "world"` ends up expanding `hello` to `world: ;` as the snippet gets detected as a property due to https://github.com/emmetio/css-snippets-resolver/blob/master/lib/snippets.js#L28
